[build]
  # This will be your default build command
  command = ""
  # This is the directory that you want to publish (default is dist folder)
  publish = "."  # Changed to use root directory

[build.environment]
  NODE_VERSION = "16"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
